logging:
  level:
    root: warn
    '[org.jmresler.fbi.nibrs]': debug
  file:
    name: logs/${spring.application.name}.log

spring:
  batch:
    jdbc:
      initialize-schema: always
      platform: h2
  datasource:
    meta:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./data/metadb
      username: app
      password: app
    nibrs:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./data/nibrs
      username: app
      password: app
      hikari:
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
      format_sql: true
      use_sql_comments: true
      show_sql: true
  sql:
    init:
      platform: h2