logging:
  level:
    root: warn
    '[org.jmresler.fbi.nibrs]': debug
  file:
    name: logs/${spring.application.name}.log

spring:
  application:
    name: batch-data-loader
  batch:
    jdbc:
      initialize-schema: always
      platform: h2
    job:
      enabled: true
  datasource:
    nibrs:
      driver-class-name: org.h2.Driver
      username: app
      password: app
      url: jdbc:h2:file:./data/nibrs;
      hikari:
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
    meta:
      driver-class-name: org.h2.Driver
      username: app
      password: app
      url: jdbc:h2:file:./data/meta
      hikari:
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    database: h2
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': true
        '[format_sql]': true
  sql:
    init:
      mode: always
