logging:
  level:
    root: warn
    '[org.jmresler.fbi.nibrs]': debug
  file:
    name: logs/${spring.application.name}.log

spring:
  batch:
    jdbc:
      platform: h2
      initialize-schema: always
  datasource:
    meta:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./data/metadb
      username: app
      password: app
    nibrs:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/nibrs
      username: root
      password: 'password'
      hikari:
        transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true