INSERT INTO ref_state
    (state_id,
     division_id,
     state_name,
     state_code,
     state_abbr,
     state_postal_abbr,
     state_fips_code,
     state_pub_freq_months,
     change_user)
VALUES (1, 10, 'Alaska', '50', 'AK', 'AK', '02', 12, ''),
       (2, 7, 'Alabama', '01', 'AL', 'AL', '01', 12, ''),
       (3, 8, 'Arkansas', '03', 'AR', 'AR', '05', 12, ''),
       (4, 1, 'American Samoa', '54', 'AS', 'AS', '60', 12, ''),
       (5, 9, 'Arizona', '02', 'AZ', 'AZ', '04', 12, ''),
       (6, 10, 'California', '04', 'CA', 'CA', '06', 12, ''),
       (7, 9, 'Colorado', '05', 'CO', 'CO', '08', 12, ''),
       (8, 2, 'Connecticut', '06', 'CT', 'CT', '09', 12, ''),
       (9, 1, 'Canal Zone', '52', 'CZ', 'CZ', '', 12, ''),
       (10, 6, 'District of Columbia', '08', 'DC', 'DC', '11', 12, '');
