spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 'password'
    url: jdbc:postgresql://localhost:5432/nibrs
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
